// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiPtmHana.DAL.DataContext;

#nullable disable

namespace WebApiPtmHana.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230515191938_EstatusSapHpInitMig")]
    partial class EstatusSapHpInitMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiPtmHana.Datos.EstadosSAP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosSap");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.EstatusHistorialPesadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstatusColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstatusHistorialPesadas");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.Lineas", b =>
                {
                    b.Property<int>("Id_linea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_linea"));

                    b.Property<bool>("Asignado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCodeLinea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("KgXHr")
                        .HasColumnType("real");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_linea");

                    b.ToTable("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
