// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiPtmHana.DAL.DataContext;

#nullable disable

namespace WebApiPtmHana.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231020231634_EnvioScrapPlantaMig")]
    partial class EnvioScrapPlantaMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiPtmHana.Datos.AcumuladoEmbarque", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("Acumulado")
                        .HasColumnType("real");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("AcumuladoEmbarques");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.BaseImpresion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdBascula")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BaseImpresion");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.BitHistorialPesadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("AnilloPTH")
                        .HasColumnType("real");

                    b.Property<float?>("AtadoPTH")
                        .HasColumnType("real");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<float?>("FlejePTH")
                        .HasColumnType("real");

                    b.Property<int>("IdHistorialPesada")
                        .HasColumnType("int");

                    b.Property<int?>("LineaPtH")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumTubosPtH")
                        .HasColumnType("int");

                    b.Property<float?>("PesoTotalPtH")
                        .HasColumnType("real");

                    b.Property<float?>("TaraPTH")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("IdHistorialPesada");

                    b.ToTable("BitHistorialPesadas");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.BitacoraAsignacionLinia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Linea")
                        .HasColumnType("int");

                    b.Property<string>("Trabajador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BitacoraAsignacionLinias");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.EnvioSAP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdHistPesada")
                        .HasColumnType("int");

                    b.Property<int>("IdentEnvioSAP")
                        .HasColumnType("int");

                    b.Property<int>("IsPrelim")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdHistPesada");

                    b.ToTable("EnvioSAP");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.EnvioScrap", b =>
                {
                    b.Property<int>("IdEnvioScrap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnvioScrap"));

                    b.Property<string>("CodigoItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Linea")
                        .HasColumnType("int");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScrapPlanta")
                        .HasColumnType("int");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEnvioScrap");

                    b.ToTable("EnvioScraps");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.EstadosPesos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Bascula")
                        .HasColumnType("int");

                    b.Property<int>("PesoBascula")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstadosPesos");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.EstadosSAP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosSap");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.EstadosSemaforo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Bascula")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstadosSemaforos");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.EstatusHistorialPesadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstatusColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstatusHistorialPesadas");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.HistorialPesadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentarioSAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEstatusHP")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstatusSAP")
                        .HasColumnType("int");

                    b.Property<int?>("Id_ProductoTerminado")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Scrap")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEstatusHP");

                    b.HasIndex("IdEstatusSAP");

                    b.HasIndex("Id_ProductoTerminado");

                    b.HasIndex("Id_Scrap");

                    b.ToTable("HistorialPesadas");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.Lineas", b =>
                {
                    b.Property<int>("Id_linea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_linea"));

                    b.Property<bool>("Asignado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolioSAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCodeLinea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KgXHr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrdenFabricacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_linea");

                    b.ToTable("Lineas");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.ProductoTerminado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("AnilloPT")
                        .HasColumnType("real");

                    b.Property<float?>("AtadoPT")
                        .HasColumnType("real");

                    b.Property<bool>("Calidad")
                        .HasColumnType("bit");

                    b.Property<string>("Clasification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPesaje")
                        .HasColumnType("datetime2");

                    b.Property<float?>("FlejePT")
                        .HasColumnType("real");

                    b.Property<float?>("FolioPT")
                        .HasColumnType("real");

                    b.Property<int?>("Id_Linea")
                        .HasColumnType("int");

                    b.Property<decimal?>("KgxHrbyPt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NumTubos")
                        .HasColumnType("int");

                    b.Property<string>("OrdenFabricacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("PesoTotal")
                        .HasColumnType("real");

                    b.Property<int?>("Planta")
                        .HasColumnType("int");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TaraPT")
                        .HasColumnType("real");

                    b.Property<int?>("TurnoPT")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Linea");

                    b.ToTable("ProductoTerminados");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.ScrapMolinos", b =>
                {
                    b.Property<int>("IdScrap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdScrap"));

                    b.Property<float>("AnilloScrpt")
                        .HasColumnType("real");

                    b.Property<float>("AtadoScrpt")
                        .HasColumnType("real");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaScrap")
                        .HasColumnType("datetime2");

                    b.Property<float>("FlejeScrpt")
                        .HasColumnType("real");

                    b.Property<int?>("IdEnvioScrap")
                        .HasColumnType("int");

                    b.Property<int>("IdRemolido")
                        .HasColumnType("int");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubFamilia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TaraScrpt")
                        .HasColumnType("real");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdScrap");

                    b.HasIndex("IdEnvioScrap");

                    b.ToTable("ScrapMolinos");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.SkuInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("AnilloCant")
                        .HasColumnType("real");

                    b.Property<float?>("ArpillaCant")
                        .HasColumnType("real");

                    b.Property<float?>("CostalesCant")
                        .HasColumnType("real");

                    b.Property<float?>("FijoCantidad")
                        .HasColumnType("real");

                    b.Property<string>("FijoCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("FlejeCant")
                        .HasColumnType("real");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("MaderaCant")
                        .HasColumnType("real");

                    b.Property<float?>("MinWeight")
                        .HasColumnType("real");

                    b.Property<float?>("MultiploCant")
                        .HasColumnType("real");

                    b.Property<string>("MultiploCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumTubos")
                        .HasColumnType("int");

                    b.Property<string>("Proceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TarimaCant")
                        .HasColumnType("real");

                    b.Property<float>("Variable")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SkuInfos");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.TicketsInfo", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicket"));

                    b.Property<bool>("AsignadoTicket")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaPesaje")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Linea")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumTubos")
                        .HasColumnType("int");

                    b.Property<int>("Operacion")
                        .HasColumnType("int");

                    b.Property<string>("OrdenFabricacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("PesoNeto")
                        .HasColumnType("real");

                    b.Property<decimal>("PesoTubo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PlantaTicket")
                        .HasColumnType("int");

                    b.Property<float?>("Porcentaje")
                        .HasColumnType("real");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.HasKey("IdTicket");

                    b.HasIndex("Id_Linea");

                    b.ToTable("TicketsInfos");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.UserTokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.BitHistorialPesadas", b =>
                {
                    b.HasOne("WebApiPtmHana.Datos.HistorialPesadas", "HistorialPesadas")
                        .WithMany()
                        .HasForeignKey("IdHistorialPesada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistorialPesadas");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.EnvioSAP", b =>
                {
                    b.HasOne("WebApiPtmHana.Datos.HistorialPesadas", "HistorialPesadas")
                        .WithMany()
                        .HasForeignKey("IdHistPesada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistorialPesadas");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.HistorialPesadas", b =>
                {
                    b.HasOne("WebApiPtmHana.Datos.EstatusHistorialPesadas", "EstatusHistorialPesadas")
                        .WithMany()
                        .HasForeignKey("IdEstatusHP");

                    b.HasOne("WebApiPtmHana.Datos.EstadosSAP", "EstadosSAP")
                        .WithMany()
                        .HasForeignKey("IdEstatusSAP");

                    b.HasOne("WebApiPtmHana.Datos.ProductoTerminado", "ProductoTerminado")
                        .WithMany()
                        .HasForeignKey("Id_ProductoTerminado");

                    b.HasOne("WebApiPtmHana.Datos.ScrapMolinos", "ScrapMolinos")
                        .WithMany()
                        .HasForeignKey("Id_Scrap");

                    b.Navigation("EstadosSAP");

                    b.Navigation("EstatusHistorialPesadas");

                    b.Navigation("ProductoTerminado");

                    b.Navigation("ScrapMolinos");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.ProductoTerminado", b =>
                {
                    b.HasOne("WebApiPtmHana.Datos.Lineas", "Lineas")
                        .WithMany()
                        .HasForeignKey("Id_Linea");

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.ScrapMolinos", b =>
                {
                    b.HasOne("WebApiPtmHana.Datos.EnvioScrap", "EnvioScrap")
                        .WithMany()
                        .HasForeignKey("IdEnvioScrap");

                    b.Navigation("EnvioScrap");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.TicketsInfo", b =>
                {
                    b.HasOne("WebApiPtmHana.Datos.Lineas", "Linea")
                        .WithMany()
                        .HasForeignKey("Id_Linea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linea");
                });
#pragma warning restore 612, 618
        }
    }
}
