// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiPtmHana.DAL.DataContext;

#nullable disable

namespace WebApiPtmHana.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230515232212_ProductoTerminadoInitMig")]
    partial class ProductoTerminadoInitMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiPtmHana.Datos.BitacoraAsignacionLinia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Linea")
                        .HasColumnType("int");

                    b.Property<string>("Trabajador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BitacoraAsignacionLinias");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.EstadosSAP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosSap");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.EstatusHistorialPesadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstatusColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstatusHistorialPesadas");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.Lineas", b =>
                {
                    b.Property<int>("Id_linea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_linea"));

                    b.Property<bool>("Asignado")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCodeLinea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("KgXHr")
                        .HasColumnType("real");

                    b.Property<string>("Proceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_linea");

                    b.ToTable("Lineas");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.ProductoTerminado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("AnilloPT")
                        .HasColumnType("real");

                    b.Property<float?>("AtadoPT")
                        .HasColumnType("real");

                    b.Property<bool>("Calidad")
                        .HasColumnType("bit");

                    b.Property<string>("Clasification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPesaje")
                        .HasColumnType("datetime2");

                    b.Property<float?>("FlejePT")
                        .HasColumnType("real");

                    b.Property<float?>("FolioPT")
                        .HasColumnType("real");

                    b.Property<int?>("Id_Linea")
                        .HasColumnType("int");

                    b.Property<float?>("KgxHrbyPt")
                        .HasColumnType("real");

                    b.Property<int?>("NumTubos")
                        .HasColumnType("int");

                    b.Property<float?>("PesoTotal")
                        .HasColumnType("real");

                    b.Property<float?>("TaraPT")
                        .HasColumnType("real");

                    b.Property<int?>("TurnoPT")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Linea");

                    b.ToTable("ProductoTerminados");
                });

            modelBuilder.Entity("WebApiPtmHana.Datos.ProductoTerminado", b =>
                {
                    b.HasOne("WebApiPtmHana.Datos.Lineas", "Lineas")
                        .WithMany()
                        .HasForeignKey("Id_Linea");

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
